name: eatseasy
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_maps_flutter:
  flutter_polyline_points: ^2.0.0
  geolocator: ^9.0.0
  geocoding: ^2.0.0
  permission_handler: ^10.2.0
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  provider: ^6.1.1
  get: ^4.6.6
  flutter_vector_icons: ^2.0.0
  cached_network_image: ^3.3.0
  flutter_rating_bar: ^4.0.1
  flutter_hooks: ^0.20.3
  http: ^1.1.0
  shimmer: ^3.0.0
  glass: ^1.0.2+1
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  get_storage: ^2.1.1
  webview_flutter: ^4.4.2
  webview_flutter_android: ^3.12.1
  webview_flutter_wkwebview: ^3.9.4
  device_preview: ^1.1.0
  firebase_auth: ^4.15.2
  firebase_core: ^2.24.2
  country_picker: ^2.0.23
  flutter_otp_text_field: ^1.1.1
  firebase_database: ^10.3.8
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^17.2.1+2
  phone_otp_verification: ^1.0.3
  feedback: ^3.0.1
  flutter_phone_direct_caller: ^2.1.1
  image_picker: ^1.0.7
  firebase_storage: ^11.6.8
  device_info_plus: ^9.1.2
  flutter_dotenv: ^5.1.0
  cross_connectivity: ^3.2.0
  cloud_firestore: ^4.17.5
  pull_to_refresh: ^2.0.0
  location: ^7.0.0
  package_info: ^2.0.2
  dio: ^5.5.0+1
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  flutter_easyloading: ^3.0.5
  photo_view: ^0.15.0
  persistent_bottom_nav_bar: ^6.2.1
  loading_animation_widget: ^1.3.0
  intl: ^0.19.0
  food_icons: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/anime/
    - assets/icons/
    - .env.development
    - .env.production